db.janusgraph.index.search {
  backend = elasticsearch
  hostname = ["elasticsearch"]
  index-name = thehive
  elasticsearch.http.auth {
    type = "basic"
    basic {
      username = "elastic"
      password = "8a9OHfXa4hIBcnEsl1BAzaN2tGDstJnv8YliTjd0nwcvdLWOO77aKZLNRRgBjMfu"
    }
  }
}
